DELETE FROM FILMS_GENRES WHERE FILM_GENRE_ID < 100;
DELETE FROM FILMS_LIKES WHERE LIKE_ID < 100;
DELETE FROM FILMS_MODEL WHERE FILM_ID < 100;
DELETE FROM GENRE_DICTIONARY WHERE GENRE_ID < 100;
DELETE FROM MPA_DICTIONARY WHERE MPA_ID < 100;
DELETE FROM USERS_FRIENDS WHERE FRIENDS_ID < 100;
DELETE FROM USERS_MODEL WHERE USER_ID < 100;
DELETE FROM DIRECTORS_MODEL WHERE DIRECTOR_ID < 100;
DELETE FROM FILMS_DIRECTORS WHERE FILMS_DIRECTORS_ID < 100;
DELETE FROM EVENT_TYPES_DICTIONARY;
DELETE FROM EVENT_OPERATIONS_DICTIONARY;
DELETE FROM USERS_FEED;

ALTER TABLE FILMS_GENRES ALTER COLUMN FILM_GENRE_ID RESTART WITH 1;
ALTER TABLE FILMS_LIKES ALTER COLUMN LIKE_ID RESTART WITH 1;
ALTER TABLE FILMS_MODEL ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE GENRE_DICTIONARY ALTER COLUMN GENRE_ID RESTART WITH 1;
ALTER TABLE MPA_DICTIONARY ALTER COLUMN MPA_ID RESTART WITH 1;
ALTER TABLE USERS_FRIENDS ALTER COLUMN FRIENDS_ID RESTART WITH 1;
ALTER TABLE USERS_MODEL ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE DIRECTORS_MODEL ALTER COLUMN DIRECTOR_ID RESTART WITH 1;
ALTER TABLE FILMS_DIRECTORS ALTER COLUMN FILMS_DIRECTORS_ID RESTART WITH 1;
ALTER TABLE EVENT_TYPES_DICTIONARY ALTER COLUMN EVENT_TYPE_ID RESTART WITH 1;
ALTER TABLE EVENT_OPERATIONS_DICTIONARY ALTER COLUMN EVENT_OPERATION_ID RESTART WITH 1;
ALTER TABLE USERS_FEED ALTER COLUMN EVENT_ID RESTART WITH 1;

INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRE_DICTIONARY (GENRE_NAME) VALUES ('Боевик');

INSERT INTO MPA_DICTIONARY (RATING, RATING_DESCRIPTION) VALUES ('G', 'У фильма нет возрастных ограничений');
INSERT INTO MPA_DICTIONARY (RATING, RATING_DESCRIPTION) VALUES ('PG', 'Детям рекомендуется смотреть фильм с родителями');
INSERT INTO MPA_DICTIONARY (RATING, RATING_DESCRIPTION) VALUES ('PG-13', 'Детям до 13 лет просмотр не желателен');
INSERT INTO MPA_DICTIONARY (RATING, RATING_DESCRIPTION) VALUES ('R', 'Лицам до 17 лет просматривать фильм можно только в присутствии взрослого');
INSERT INTO MPA_DICTIONARY (RATING, RATING_DESCRIPTION) VALUES ('NC-17', 'Лицам до 18 лет просмотр запрещён');

INSERT INTO EVENT_TYPES_DICTIONARY (EVENT_TYPE) VALUES ('LIKE');
INSERT INTO EVENT_TYPES_DICTIONARY (EVENT_TYPE) VALUES ('REVIEW');
INSERT INTO EVENT_TYPES_DICTIONARY (EVENT_TYPE) VALUES ('FRIEND');

INSERT INTO EVENT_OPERATIONS_DICTIONARY (EVENT_OPERATION) VALUES ('REMOVE');
INSERT INTO EVENT_OPERATIONS_DICTIONARY (EVENT_OPERATION) VALUES ('ADD');
INSERT INTO EVENT_OPERATIONS_DICTIONARY (EVENT_OPERATION) VALUES ('UPDATE');