CREATE TABLE IF NOT EXISTS users_model (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar unique,
    login varchar unique,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS users_friends (
    friends_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES users_model(user_id),
    user_friend_id int REFERENCES users_model(user_id)
);

CREATE TABLE IF NOT EXISTS genre_dictionary (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar,
    genre_description varchar
);

CREATE TABLE IF NOT EXISTS mpa_dictionary (
    mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating varchar,
    rating_description varchar
);

CREATE TABLE IF NOT EXISTS films_model (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar,
    description varchar,
    release_date date,
    duration BIGINT,
    mpa_id int REFERENCES mpa_dictionary(mpa_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int REFERENCES films_model(film_id),
    genre_id int REFERENCES genre_dictionary(genre_id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    like_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int REFERENCES films_model(film_id),
    user_id int REFERENCES users_model(user_id)
);