delete from FILMORATETEST.PUBLIC.FILM;
delete from FILMORATETEST.PUBLIC.FILM_GENRE;
delete from FILMORATETEST.PUBLIC.USERS;
delete from FILMORATETEST.PUBLIC.LIKE_USER_FILM;
ALTER TABLE FILMORATETEST.PUBLIC.FILM ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE FILMORATETEST.PUBLIC.USERS ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILMORATETEST.PUBLIC.LIKE_USER_FILM ALTER COLUMN ID RESTART WITH 1;

