delete from FILMORATETEST.PUBLIC.USERS;
delete from FILMORATETEST.PUBLIC.FRIEND;
ALTER TABLE FILMORATETEST.PUBLIC.USERS ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILMORATETEST.PUBLIC.FRIEND ALTER COLUMN ID RESTART WITH 1;